language: node_js
dist: trusty

node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "lumenol-github"   
 
script:
  - npm test -- --coverage --watchAll=false --passWithNoTests
  - npm run build
  - bash <(curl -s https://codecov.io/bash)
  - npm run sonarqube

  
